on: [issue_comment]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: akleinau/githubJSActions/DiscussedToColumn@master
     # with:

