on: [issue_comment]

jobs:
  FindOutHowManyComments:
    runs-on: ubuntu-latest
    name: aJobThatMoves
    steps:
    - name: count
      id: count
      uses: akleinau/githubJSActions/DiscussedToColumn@master
    - name: printit
      run: echo ${{ steps.count.outputs.continue }}
     # with:
    - name: add-new-issues-to-repository-based-project-column
      uses: docker://takanabe/github-actions-automate-projects:v0.0.1
      if: steps.count.outputs.continue == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_PROJECT_URL: https://github.com/akleinau/githubJSActions/projects/1
        GITHUB_PROJECT_COLUMN_NAME: In discussion