on: [issue_comment]

jobs:
  FindOutHowManyComments:
    runs-on: ubuntu-latest
    name: aJobThatMoves
    steps:
    - name: count
      id: count
      uses: akleinau/githubJSActions/DiscussedToColumn@master
    - name: printit
      run: echo ${{ steps.count.outputs.continue }} 
    - name: addToColumn 
      - uses: alex-page/github-project-automation-plus@v0.2.4
        with:
          project: Issues
          column: In discussion
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      if: steps.count.outputs.continue == 'true'
